name: 'Run tests in Renode'
description: 'This action runs selected robot test suites in Renode and generates artifacts'
author: 'Antmicro'

branding:
  color: 'blue'
  icon: 'play-circle'

inputs:
  renode-revision:
    description: 'Renode git revision (can be a branch name, tag, commit sha, etc)'
    required: true
    default: 'master'
  renode-repository:
    description: 'Renode git repository'
    required: true
    default: 'https://github.com/renode/renode'
  renode-resource-repository:
    description: 'Renode binary resources git repository'
    required: true
    default: 'https://github.com/renode/renode-resources'
  tests-to-run:
    description: 'Robot framework test paths'
    required: false
  renode-arguments:
    description: 'Additional arguments passed to renode-test'
    required: false
    default: ''
  artifacts-path:
    description: 'Path where renode-test artifacts should be stored'
    required: false
    default: '.'
  gather-execution-metrics:
    description: 'Gather execution metrics for executed binaries'
    required: false
    default: 'no'
  install-dependencies:
    description: 'Install dependencies before building Renode (requires sudo privileges, Linux specific)'
    required: false
    default: 'yes'
  disable-summary-generation:
    description: 'Disables step summary generation'
    required: false
    default: 'no'
runs:
  using: "composite"
  steps:
    - id: get-renode-rev
      run: |
        git clone "${{ inputs.renode-repository }}" renode
        git -C renode checkout "${{ inputs.renode-revision }}" --
        rev="$(git -C renode rev-parse @)"
        # Increment to force cache invalidation.
        action_hash_key=0
        echo "renode-rev=$rev" >> "$GITHUB_OUTPUT"
        echo "action-hash-key=$action_hash_key" >> "$GITHUB_OUTPUT"
        git clone "${{ inputs.renode-resource-repository }}" renode/lib/resources
        mv renode "renode-$rev-cloned"
      shell: bash
      working-directory: ${{ github.workspace }}
      # Avoid the download/build steps if Renode is already installed. We can't just put all of the build steps
      # into a nested composite action as it wouldn't be available when using this action from another repository.
      # See https://github.com/orgs/community/discussions/66094
      if: ${{ env.RENODE_ROOT == '' }}
    - uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: ${{ github.workspace }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
        key: renode-${{ runner.os }}-${{ runner.arch }}-${{ steps.get-renode-rev.outputs.renode-rev }}-${{ steps.get-renode-rev.outputs.action-hash-key }}
      if: ${{ env.RENODE_ROOT == '' }}
    # Remove the just-cloned source if a cached build was found
    - run: |
        rm -rf renode-${{ steps.get-renode-rev.outputs.renode-rev }}-cloned
      shell: bash
      working-directory: ${{ github.workspace }}
      if: ${{ env.RENODE_ROOT == '' && steps.restore-cache.outputs.cache-hit == 'true' }}
    - run: |
        mv renode-${{ steps.get-renode-rev.outputs.renode-rev }}-cloned renode-${{ steps.get-renode-rev.outputs.renode-rev }}
        cd renode-${{ steps.get-renode-rev.outputs.renode-rev }}
        echo Building "${{ inputs.renode-repository }}" at "${{ inputs.renode-revision }} (${{ steps.get-renode-rev.outputs.renode-rev }})"
        git submodule update --init --recursive --depth=1
      shell: bash
      working-directory: ${{ github.workspace }}
      if: ${{ env.RENODE_ROOT == '' && steps.restore-cache.outputs.cache-hit != 'true' }}
    - name: Install dependencies (Linux)
      run: |
        source ubuntu-dependencies
        sudo apt-get -qqy update
        sudo apt-get -y install --no-install-recommends ${RENODE_DEPENDENCIES[@]}
      shell: bash
      if: ${{ inputs.install-dependencies == 'yes' && env.RENODE_ROOT == '' && runner.os == 'Linux' }}
    - name: Verify dependencies (Linux)
      run: |
        source ubuntu-dependencies
        fail=0
        for pkg in ${RENODE_DEPENDENCIES[@]}
        do
          dpkg-query -W $pkg > /dev/null || fail=1
        done
        exit $fail
      shell: bash
      if: ${{ inputs.install-dependencies != 'yes' && env.RENODE_ROOT == '' && runner.os == 'Linux' }}
    - name: Build Renode
      run: |
        ./build.sh --net
      shell: bash
      working-directory: ${{ github.workspace }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
      if: ${{ env.RENODE_ROOT == '' && runner.os != 'Windows' && steps.restore-cache.outputs.cache-hit != 'true' }}
    - name: Build Renode (Windows)
      run: |
        msbuild="$(vswhere -latest -requires Microsoft.Component.MSBuild -find 'MSBuild\**\Bin\MSBuild.exe' | tr '\\' '/')"
        export PATH="$PATH:$(cygpath "$(dirname "$msbuild")"):$PWD"
        export MSYS=winsymlinks:nativestrict
        ./build.sh --net
        cp $GITHUB_ACTION_PATH/src/renode_test_windows.sh renode-test
      shell: bash
      working-directory: ${{ github.workspace }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
      if: ${{ env.RENODE_ROOT == '' && runner.os == 'Windows' && steps.restore-cache.outputs.cache-hit != 'true' }}
    - name: Delete files to slim down cache
      run: |
        find . -name .git -exec rm -rf '{}' '+'
        find lib src '(' -name bin -or -name obj ')' -exec rm -rf '{}' '+'
      shell: bash
      working-directory: ${{ github.workspace }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
      if: ${{ env.RENODE_ROOT == '' && steps.restore-cache.outputs.cache-hit != 'true' }}
    - uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
        key: renode-${{ runner.os }}-${{ runner.arch }}-${{ steps.get-renode-rev.outputs.renode-rev }}-${{ steps.get-renode-rev.outputs.action-hash-key }}
      if: ${{ env.RENODE_ROOT == '' && steps.restore-cache.outputs.cache-hit != 'true' }}
    - name: Install Robot framework dependencies
      run: python3 -m pip install -r tests/requirements.txt
      shell: bash
      working-directory: ${{ github.workspace }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
      if: ${{ env.RENODE_ROOT == '' }}
    - name: Install Robot framework dependencies under py on Windows
      run: py -3 -m pip install -r tests/requirements.txt
      shell: bash
      working-directory: ${{ github.workspace }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
      if: ${{ env.RENODE_ROOT == '' && runner.os == 'Windows' }}
    - name: Setup environment
      run: |
        echo "${{ github.workspace }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}" >> "$GITHUB_PATH"
        echo "RENODE_ROOT=${{ github.workspace }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}" >> "$GITHUB_ENV"
      shell: bash
      if: ${{ env.RENODE_ROOT == '' }}
    - run: $GITHUB_ACTION_PATH/src/run_renode_test.sh
      shell: bash
      env:
        TESTS_TO_RUN: ${{ inputs.tests-to-run }}
        RENODE_ARGUMENTS: ${{ inputs.renode-arguments }}
        ARTIFACTS_PATH: ${{ inputs.artifacts-path }}
        EXECUTION_METRICS: ${{ inputs.gather-execution-metrics }}
        RENODE_NO_STEP_SUMMARY: ${{ inputs.disable-summary-generation == 'yes' && '1' || '' }}
