name: Test action

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      renode_revision:
        description: 'Renode git revision'
        required: false
        default: ''
      renode_repository:
        description: 'Renode git repository'
        required: false
        default: ''

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          renode-revision: 'master'
          tests-to-run: 'tests/platforms/zynqmp.robot'
  test-windows:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          renode-revision: 'master'
          tests-to-run: 'tests/platforms/zynqmp.robot'
